version: '3'

services:
  lab:
    build:
      context: .
      dockerfile: ./lab.Dockerfile
    container_name: lune
    network_mode: "host"
    command: ["/bin/bash", "-c", "jupyter lab --ip 0.0.0.0 --port=50000 --no-browser --allow-root --notebook-dir=/mnt"]
    volumes:
      - /mnt/:/mnt/
    privileged: true
    tmpfs:
      - /mnt/tmpfs
    shm_size: 16G
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
